process_groups:
  - name: "executor"
    replicas: 4
    command: "./actions/venv/bin/python3"
    script: "./actions/main.py"
    arg_prefix: "-"
    arg_assign: "="
    args:
      group:
      - flag: execution-group-id
      - flag: video-path
      - flag: model-path
      - flag: model-config-path
      - flag: code-path
      - flag: video-token
