process_groups:
  - name: "executor"
    replicas: 3
    command: "/app/venv/bin/python3"
    script: "/app/executor/main.py"
    arg_prefix: "-"
    arg_assign: "="
    args:
      group:
      - flag: video-path
      - flag: model-path
      - flag: model-config-path
      process:
      - - flag: port
          value: 5050
      - - flag: port
          value: 5051
