process_groups:
  - name: "executor"
    replicas: 3
    command: "../executor/venv/bin/python3"
    script: "../executor/main.py"
    arg_prefix: "-"
    arg_assign: "="
    args:
      - flag: video-path
      - flag: model-path
      - flag: model-config-path
