name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Go setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check Go Build
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install -y -qq libzmq3-dev&&  \
        cd orchestrator && make build
        
    - name: Check Python Code
      run: |
        sudo apt-get install -y -qq python3 python3-dev virtualenv
        virtualenv --python=python3 venv
        source ./venv/bin/activate
        pip install flake8
        cd executor && flake8 .

    
    #- name: Test
     # run: go test -v .